//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiTiErp.Reports.ThayHopDongDien {
    
    public partial class repThayHDTS : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "NiTiErp.Reports.ThayHopDongDien.repThayHDTS.repx");

            // Controls
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.detailBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("detailBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.label23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label23");
            this.label22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label22");
            this.label20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label20");
            this.label16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label16");
            this.label15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label15");
            this.label14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label14");
            this.label13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label13");
            this.label12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label12");
            this.label10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label10");
            this.label9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label9");
            this.label8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label8");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");
            this.label6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label6");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");

            // Parameters
            this.prTenKH = reportInitializer.GetParameter("prTenKH");
            this.prSoHDMoi = reportInitializer.GetParameter("prSoHDMoi");
            this.prDiaChiLD = reportInitializer.GetParameter("prDiaChiLD");
            this.prDanhSo = reportInitializer.GetParameter("prDanhSo");
            this.prNgayHieuLuc = reportInitializer.GetParameter("prNgayHieuLuc");
            this.prNgayKyHD = reportInitializer.GetParameter("prNgayKyHD");
            this.prThangKyHD = reportInitializer.GetParameter("prThangKyHD");
            this.prNamKyHD = reportInitializer.GetParameter("prNamKyHD");
            this.prTaiXN = reportInitializer.GetParameter("prTaiXN");
            this.prNguoiDaiDien = reportInitializer.GetParameter("prNguoiDaiDien");
            this.prNguoiUyQuyen = reportInitializer.GetParameter("prNguoiUyQuyen");
            this.prTenChucVu = reportInitializer.GetParameter("prTenChucVu");
            this.prCMND = reportInitializer.GetParameter("prCMND");
            this.prNgayCap = reportInitializer.GetParameter("prNgayCap");
            this.prThangCap = reportInitializer.GetParameter("prThangCap");
            this.prNamCap = reportInitializer.GetParameter("prNamCap");
            this.prTaiDau = reportInitializer.GetParameter("prTaiDau");
            this.prSoGiayUyQuyen = reportInitializer.GetParameter("prSoGiayUyQuyen");
            this.prNgayUyQuyen = reportInitializer.GetParameter("prNgayUyQuyen");
            this.prDiaChiKH = reportInitializer.GetParameter("prDiaChiKH");
            this.prMaSoThueMoi = reportInitializer.GetParameter("prMaSoThueMoi");
            this.prDienThoai = reportInitializer.GetParameter("prDienThoai");
            this.prNgayHLHD = reportInitializer.GetParameter("prNgayHLHD");
            this.prThangHLHD = reportInitializer.GetParameter("prThangHLHD");
            this.prNamKyHLHD = reportInitializer.GetParameter("prNamKyHLHD");
            this.prMaKhachHangPo = reportInitializer.GetParameter("prMaKhachHangPo");
        }
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.DetailBand detailBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.XRLabel label23;
        private DevExpress.XtraReports.UI.XRLabel label22;
        private DevExpress.XtraReports.UI.XRLabel label20;
        private DevExpress.XtraReports.UI.XRLabel label16;
        private DevExpress.XtraReports.UI.XRLabel label15;
        private DevExpress.XtraReports.UI.XRLabel label14;
        private DevExpress.XtraReports.UI.XRLabel label13;
        private DevExpress.XtraReports.UI.XRLabel label12;
        private DevExpress.XtraReports.UI.XRLabel label10;
        private DevExpress.XtraReports.UI.XRLabel label9;
        private DevExpress.XtraReports.UI.XRLabel label8;
        private DevExpress.XtraReports.UI.XRLabel label7;
        private DevExpress.XtraReports.UI.XRLabel label6;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.Parameters.Parameter prTenKH;
        private DevExpress.XtraReports.Parameters.Parameter prSoHDMoi;
        private DevExpress.XtraReports.Parameters.Parameter prDiaChiLD;
        private DevExpress.XtraReports.Parameters.Parameter prDanhSo;
        private DevExpress.XtraReports.Parameters.Parameter prNgayHieuLuc;
        private DevExpress.XtraReports.Parameters.Parameter prNgayKyHD;
        private DevExpress.XtraReports.Parameters.Parameter prThangKyHD;
        private DevExpress.XtraReports.Parameters.Parameter prNamKyHD;
        private DevExpress.XtraReports.Parameters.Parameter prTaiXN;
        private DevExpress.XtraReports.Parameters.Parameter prNguoiDaiDien;
        private DevExpress.XtraReports.Parameters.Parameter prNguoiUyQuyen;
        private DevExpress.XtraReports.Parameters.Parameter prTenChucVu;
        private DevExpress.XtraReports.Parameters.Parameter prCMND;
        private DevExpress.XtraReports.Parameters.Parameter prNgayCap;
        private DevExpress.XtraReports.Parameters.Parameter prThangCap;
        private DevExpress.XtraReports.Parameters.Parameter prNamCap;
        private DevExpress.XtraReports.Parameters.Parameter prTaiDau;
        private DevExpress.XtraReports.Parameters.Parameter prSoGiayUyQuyen;
        private DevExpress.XtraReports.Parameters.Parameter prNgayUyQuyen;
        private DevExpress.XtraReports.Parameters.Parameter prDiaChiKH;
        private DevExpress.XtraReports.Parameters.Parameter prMaSoThueMoi;
        private DevExpress.XtraReports.Parameters.Parameter prDienThoai;
        private DevExpress.XtraReports.Parameters.Parameter prNgayHLHD;
        private DevExpress.XtraReports.Parameters.Parameter prThangHLHD;
        private DevExpress.XtraReports.Parameters.Parameter prNamKyHLHD;
        private DevExpress.XtraReports.Parameters.Parameter prMaKhachHangPo;
    }
}
